"""
new_blur_effect.py
A new approach to apply blur effect on instance.
This method blurs the original image and redo the instance segmentation
by the original instance information generated by the model.

Created by Chikuma 2019/10/14
"""
import cv2 as cv
import numpy as np
import builder

def blurEffect (image, maskResults, instanceIndex, filterSize=3):
    filter = np.ones((filterSize, filterSize), dtype = np.float32) / (filterSize**2)
    image = cv.filter2D(image, -1, filter)
    instanceBuilder = builder.Builder()
    root = instanceBuilder.build(image, maskResults)[0]
    return root.getChildByIndex(instanceIndex)
